### ISSUE TITLE
建议将 podspec 下载地址更换国内的服务器。

### ISSUE THREAD

**Issue by VincentSit** [MobClub/ShareSDK3.x-for-iOS#10]
SDK 太大，即使翻墙了国内下载速度依然不理想。希望把下载路径更改为国内的或者你们自己的服务器。

国外下载国内的不会这么慢。

**Comment by ByteRax** [comment]
+1

**Comment by patgdut** [comment]
对，真的超级慢...

**Comment by weiweiXue** [comment]
下不了。。。没人解决这个问题吗，问客服也没人搭理。。

**Comment by l900416** [comment]
更新不了+1，v3.4.2
这都没人管吗？

**Comment by JinghuangLiu** [comment]
ShareSDK国外用户也很多。翻下墙或开个设置VPN就很快的。

发自我的 iPhone

**Comment by l900416** [comment]
看来你们看中的主要用户群体在国外

**Comment by JinghuangLiu** [comment]
非IDFA版本的源：https://git.oschina.net/MobClub/ShareSDK-for-iOS.git

IDFA版本的源（如果同时使用了mob.com平台的SMSSDK，一定要用这个源）：https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git
