### ISSUE TITLE
微信的sdk升级了，支持ipv6 你们的是不是也要升级？

### ISSUE THREAD

**Issue by zhiliang729** [MobClub/ShareSDK3.x-for-iOS#11]
微信的sdk升级了，支持ipv6 你们的是不是也要升级？ 微信的通知连接:https://open.weixin.qq.com/cgi-bin/announce?action=getannouncement&key=1463034609&version=5&lang=zh_CN#rd

**Comment by liuwin7** [comment]
+1

**Comment by DangerousDON** [comment]
ShareSDK本身不受本次苹果政策调整影响。但是ShareSDK里面包含到的第三方SDK，例如微信SDK，是需要更新的。至于除了微信SDK以外的其他第三方SDK，如果有更新，ShareSDK也会确保使用最新版本的第三方SDK。

**Comment by JinghuangLiu** [comment]
ShareSDK本身不需要，我们下周更新，着急的话可以自已替换掉微信SDK就可以了

发自我的 iPhone

**Comment by zhiliang729** [comment]
ok
