### ISSUE TITLE
缺少ShareSDKExtension库导致调用默认分享界面crash

### ISSUE THREAD

**Issue by CrashRain** [MobClub/ShareSDK3.x-for-iOS#20]
缺少ShareSDKExtension库导致调用默认分享界面crash，提示+[ShareSDK isClientInstalled]方法未定义，而该方法在ShareSDKExtension库中

自己找的解决办法是：
从官网下载最新的SDK，提取里面的ShareSDKExtension.framework放到项目中即可.

**Comment by JinghuangLiu** [comment]
是这样的，我们新版更新说明有说到。
