### ISSUE TITLE
用最新的cocoapod 1.1.1版本,libwechatsdk.a 冲突

### ISSUE THREAD

**Issue by c137Choi** [MobClub/ShareSDK3.x-for-iOS#22]
用1.1.1版本的cocoapod 集成微信分享时, libwechatsdk.a 和 BeeCloud的微信 libwechatsdk.a 冲突, 无法安装成功.

**Comment by liufangli520** [comment]
https://www.mob.com/wiki/detailed/?wiki=ShareSDK_ios_pod_share_pods&id=14 首先请根据这个文档用最新的，ShareSDK3这个不维护了，其次一个项目里只能导入一个微信sdk，不能有多个微信sdk，可以直接用我们sdk里的微信sdk
