### ISSUE TITLE
3.5.3 没有发布到 pod 官方 specs 仓库

### ISSUE THREAD

**Issue by EkkoG** [MobClub/ShareSDK3.x-for-iOS#26]
https://github.com/CocoaPods/Specs/tree/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/1/2/d/ShareSDK3

**Comment by JinghuangLiu** [comment]
升级了CocoaPods后遇到坑，解决中。

发自我的 iPhone

**Comment by EkkoG** [comment]
麻烦更新好的话通知一下 😂

**Comment by JinghuangLiu** [comment]
好的

发自我的 iPhone

**Comment by JinghuangLiu** [comment]
反馈给CocoaPods的人了，但还没修复。暂时可以在命令后加上下载源地址，类似这样：

pod 'ShareSDK3',:git => 'https://github.com/MobClub/ShareSDK3.x-for-iOS.git'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKPlatforms/QQ',:git => 'https://github.com/MobClub/ShareSDK3.x-for-iOS.git'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo',:git => 'https://github.com/MobClub/ShareSDK3.x-for-iOS.git'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat',:git => 'https://github.com/MobClub/ShareSDK3.x-for-iOS.git'

**Comment by Fighting-MrWeng** [comment]
现在更新上去了吗？

**Comment by JinghuangLiu** [comment]
稍等 测试中

发自我的 iPhone

**Comment by Fighting-MrWeng** [comment]
ShareSDK3/ShareSDKUI 这个pod 最新版也是pod 'ShareSDK3/ShareSDKUI',:git => 'https://github.com/MobClub/ShareSDK3.x-for-iOS.git' 这样吗？

**Comment by JinghuangLiu** [comment]
是的
