### ISSUE TITLE
鉴于国内的网络(你懂的), 能否把源地址更改到其他代码托管平台呢?

### ISSUE THREAD

**Issue by Initial-C** [MobClub/ShareSDK3.x-for-iOS#30]
每次更新这个库都得等半天, 还不一定能更新成功, 作者大大, 能否把源地址替换为国内其他代码托管平台呢?

**Comment by JinghuangLiu** [comment]
可以 马上弄 放在开源中国的码云上 地址待会给过去

发自我的 iPhone

**Comment by JinghuangLiu** [comment]
非IDFA版本的源：https://git.oschina.net/MobClub/ShareSDK-for-iOS.git

IDFA版本的源（如果同时使用了mob.com平台的SMSSDK，一定要用这个源）：https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git

**Comment by Initial-C** [comment]
[cid:04690E84-7028-4FDA-9CF9-E0EF7FF9FC22]
强制更换依赖源地址, 会报错呢, 请问有什么解决方案呢?
在 2016年12月22日，14:21，刘靖煌 <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #30<https://github.com/MobClub/ShareSDK3.x-for-iOS/issues/30>.

**Comment by JinghuangLiu** [comment]
报什么错

发自我的 iPhone

**Comment by Initial-C** [comment]
[cid:933A7DF6-4CE0-43BB-9BCA-296CC2F491B9]

在 2016年12月22日，19:56，刘靖煌 <notifications@github.com<mailto:notifications@github.com>> 写道：

报什么错

发自我的 iPhone

**Comment by JinghuangLiu** [comment]
手机（手机safari也）看不到，在开会，晚些吧

发自我的 iPhone

**Comment by Initial-C** [comment]
还有一个问题就是, 在cocoapods podfile文件中如果同时pod ’SMSSDK’和 ‘ShareSDK3’, cocoapods会报错, 由于Mob这次更新, SMSSDK和ShareSDK3内部同时依赖MOBFoundation_IDFA, 会报重复依赖错误, 望解决[cid:531E80DC-15AE-413E-B246-8D0F36996494]

在 2016年12月22日，19:59，刘靖煌 <notifications@github.com<mailto:notifications@github.com>> 写道：

手机（手机safari也）看不到，在开会，晚些吧

发自我的 iPhone

**Comment by JinghuangLiu** [comment]
重复依赖同一个没问题。问题不是同一个，所以我才另开了一个源，让它们依赖同一个。

发自我的 iPhone

**Comment by Initial-C** [comment]
: [cid:2D5C97BA-9144-472B-9B63-6F4848DA0B3C]
[cid:12F828B4-35EC-41EB-901F-29FC1828FBBD]
如上所示,
pod ’SMSSDK’
pod ’ShareSDK3’
会下载[cid:7FD35B37-CC74-4FB4-ABC4-F1F0017F9F5C]
而这两个公共库里的文件会重复, 导致这个错误:
[cid:96461CB9-A31F-4CF6-96F7-C6EE5823B87D]
==========================

在 2016年12月22日，20:48，刘靖煌 <notifications@github.com<mailto:notifications@github.com>> 写道：


重复依赖同一个没问题。问题不是同一个，所以我才另开了一个源，让它们依赖同一个。

发自我的 iPhone

> 在 2016年12月22日，下午8:45，William Chang <notifications@github.com<mailto:notifications@github.com>> 写道：
>
> 还有一个问题就是, 在cocoapods podfile文件中如果同时pod ’SMSSDK’和 ‘ShareSDK3’, cocoapods会报错, 由于Mob这次更新, SMSSDK和ShareSDK3内部同时依赖MOBFoundation_IDFA, 会报重复依赖错误, 望解决[cid:531E80DC-15AE-413E-B246-8D0F36996494]
>

**Comment by JinghuangLiu** [comment]
![2016-12-22 9 00 58](https://cloud.githubusercontent.com/assets/6930613/21426405/b62c7964-c889-11e6-90f7-7908478d1d23.png)

原来不是手机打不开。

**Comment by JinghuangLiu** [comment]
总结发你吧。

ShareSDK关于CocoaPods源的说明：
只使用ShareSDK的用户，CocoaPods本身的或以下的不含IDFA版本的源都适用。
如果同时使用了mob.com平台的SMSSDK，一定要用IDFA版本的源。

国内服务器的源：
不含IDFA版本的源：https://git.oschina.net/MobClub/ShareSDK-for-iOS.git
IDFA版本的源：https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git

国外服务器的源：
不含IDFA版本的源：https://github.com/MobClub/ShareSDK3.x-for-iOS.git
IDFA版本的源：https://github.com/MobClub/ShareSDK-for-iOS-Spec.git

**Comment by JinghuangLiu** [comment]
用国内服务器的IDFA版本的源吧，下载时更快，就是要加个源地址麻烦些。
这是CocoaPods更新后最好的解决方案了。

**Comment by Initial-C** [comment]
等您抽个空再解决吧, 我暂时指定用回ShareSDK3.4.2, SMSSDK2.0.4
在 2016年12月22日，21:01，刘靖煌 <notifications@github.com<mailto:notifications@github.com>> 写道：


[2016-12-22 9 00 58]<https://cloud.githubusercontent.com/assets/6930613/21426405/b62c7964-c889-11e6-90f7-7908478d1d23.png>

原来不是手机打不开。

**Comment by Initial-C** [comment]
如何更换源呢? 我使用: pod ’ShareSDK3’, :git => ‘国内源地址’  会报错呢
在 2016年12月22日，21:03，刘靖煌 <notifications@github.com<mailto:notifications@github.com>> 写道：


用国内服务器的IDFA版本的源吧，下载时更快，就是要加个源地址麻烦些。
这是CocoaPods更新后最好的解决方案了。

**Comment by JinghuangLiu** [comment]
能解决我就解决掉了。SMSSDK一定要依赖IDFA版本公共库，ShareSDK发布到CocoaPods服务器的用不含IDFA版本的（大多人还是需要不含IDFA版本的）。

类似这样就可以了：

pod 'ShareSDK3',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'
pod 'ShareSDK3/ShareSDKUI',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'
pod 'ShareSDK3/ShareSDKPlatforms/QQ',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'

#SMS短信验证
pod 'SMSSDK'

**Comment by Initial-C** [comment]
非常感谢 🙏
在 2016年12月22日，21:07，刘靖煌 <notifications@github.com<mailto:notifications@github.com>> 写道：


能解决我就解决掉了。SMSSDK一定要依赖IDFA版本公共库，ShareSDK发布到CocoaPods服务器的用不含IDFA版本的（大多人还是需要不含IDFA版本的）。

类似这样就可以了：

主模块(必须)

pod 'ShareSDK3',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'
#pod 'MOBFoundation'

UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)

pod 'ShareSDK3/ShareSDKUI',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'

平台SDK模块(对照一下平台，需要的加上，如果只需要QQ、微信、新浪微博，只需要以下3行)

pod 'ShareSDK3/ShareSDKPlatforms/QQ',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'

#SMS短信验证
pod 'SMSSDK'

**Comment by Initial-C** [comment]
对了, 我使用私有库配置时, s.dependency 是不支持 :git => ‘地址’ 指定的, 由于项目必须同时用到Mob的SMSSDK(必须用到IDFA)和ShareSDK, 所以麻烦您在'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'中更新podspec文件名, pod 依赖名改成如 : ShareSDK3_IDFA 的, 毕竟是针对不同用户群体的
在 2016年12月22日，21:07，刘靖煌 <notifications@github.com<mailto:notifications@github.com>> 写道：


能解决我就解决掉了。SMSSDK一定要依赖IDFA版本公共库，ShareSDK发布到CocoaPods服务器的用不含IDFA版本的（大多人还是需要不含IDFA版本的）。

类似这样就可以了：

主模块(必须)

pod 'ShareSDK3',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'
#pod 'MOBFoundation'

UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)

pod 'ShareSDK3/ShareSDKUI',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'

平台SDK模块(对照一下平台，需要的加上，如果只需要QQ、微信、新浪微博，只需要以下3行)

pod 'ShareSDK3/ShareSDKPlatforms/QQ',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat',:git => 'https://git.oschina.net/MobClub/ShareSDK-for-iOS-Spec.git'

#SMS短信验证
pod 'SMSSDK'

**Comment by JinghuangLiu** [comment]
������QQ��642270023������������������������������������������������

�������� iPhone

> �� 2016��12��22��������9:59��William Chang <notifications@github.com> ������
> 
> ShareSDK3_IDFA

**Comment by Initial-C** [comment]
已加, 备注: coder: 张伟诚
在 2016年12月22日，22:09，刘靖煌 <notifications@github.com<mailto:notifications@github.com>> 写道：

������QQ��642270023������������������������������������������������

�������� iPhone
