### ISSUE TITLE
不能初始化 SDK，卡死在 [MOBFDataService cacheDataForDomain:hasInTrans:]

### ISSUE THREAD

**Issue by EkkoG** [MobClub/ShareSDK3.x-for-iOS#39]
![image](https://cloud.githubusercontent.com/assets/3138493/25832972/c2e445aa-34a0-11e7-8e17-18e8d387d910.png)

系统版本 iPhone OS 10.3.1 (14E304)

**Comment by EkkoG** [comment]
@JinghuangLiu 又一个卡主线程的问题

**Comment by anplex** [comment]
麻烦联系下我们客服 http://www.mob.com 主页上有联系方式

**Comment by EkkoG** [comment]
好的
