### ISSUE TITLE
cocoapods安装后，怎么无法import framework

### ISSUE THREAD

**Issue by hengchengfei** [MobClub/ShareSDK3.x-for-iOS#4]
为何安装成功，并且编译成功后，无法导入framework呢。（添加时，搜索不到ShareSDK）

**Comment by JinghuangLiu** [comment]
加下我们技术支持的QQ：4006852216，让他们帮忙看下

**Comment by hengchengfei** [comment]
OK，已经解决

**Comment by JinghuangLiu** [comment]
使用swift编写程序的，因为SDK是Objective-C，应该在架桥文件中添加头文件，可以参考我们官方提供的Demo。

**Comment by hengchengfei** [comment]
官方Demo没有使用Cocoapods，所以建议用pod方式作为参考会比较好。
