### ISSUE TITLE
请问为什么不是能过Pod集成微信的SDK呢？

### ISSUE THREAD

**Issue by guoweikun621** [MobClub/ShareSDK3.x-for-iOS#43]
引入ShareSDK后，再通过pod集成微信SDK会报错，已经存在了a文件。手动集成也报错。而且还不能直接引用ShareSDK里面的微信SDK。

望修复。

**Comment by liufangli520** [comment]
您要集成微信原生的东西，直接用我们sdk里导入的微信sdk就行了，不需要在去加原生的sdk 了哦
