### ISSUE TITLE
官网已经是4.0.7了，这边会更新吗？

### ISSUE THREAD

**Issue by cythb** [MobClub/ShareSDK3.x-for-iOS#45]
https://github.com/MobClub/ShareSDK-for-iOS
这个仓库是最新的，但是没有发布到Cocoapods

**Comment by liufangli520** [comment]
> https://github.com/MobClub/ShareSDK-for-iOS
> 这个仓库是最新的，但是没有发布到Cocoapods

pod上也已经是最新版本了哈，https://www.mob.com/wiki/detailed/?wiki=ShareSDK_ios_pod_share_pods&id=14 看这个文档
