### ISSUE TITLE
sina的包不是最新的？

### ISSUE THREAD

**Issue by zhiliang729** [MobClub/ShareSDK3.x-for-iOS#6]
archive 的时候 bitcode失败

**Comment by zhiliang729** [comment]
新浪微博的sdk  archive的时候 报错   bitcode bundle could not be generated because '/Users/**************/Pods/ShareSDK3/libraries/extends/SinaWeiboSDK/libWeiboSDK.a(WBSDKNormalWebViewController.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

**Comment by zhiliang729** [comment]
若最近不在release版本，可以把 pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'  替换为  pod 'WeiboSDK', :git => 'https://github.com/sinaweibosdk/weibo_ios_sdk.git'

**Comment by speedpursuer** [comment]
@zhiliang729 请问你新浪微博的sdk archive这个问题解决了吗？是通过disable bitcode解决的吗？谢谢！

**Comment by JinghuangLiu** [comment]
看下mob.com ShareSDK最新的更新说明

发自我的 iPhone

**Comment by speedpursuer** [comment]
@JinghuangLiu 你好，刚看了下，没找到相关页面，请帮忙给个链接好吗？谢谢！

**Comment by JinghuangLiu** [comment]
加我QQ：642270024

发自我的 iPhone
