### ISSUE TITLE
最新版pod编译不通过啊

### ISSUE THREAD

**Issue by hengchengfei** [MobClub/ShareSDK3.x-for-iOS#8]
3.1.4升级到3.1.8编译失败了。

![1](https://cloud.githubusercontent.com/assets/3182964/12389548/6e79536a-be14-11e5-995f-67059154de87.jpg)

**Comment by JinghuangLiu** [comment]
编译失败，提示什么

发自我的 iPhone

**Comment by hengchengfei** [comment]
已经截图了啊。

环境：XCode7.2

<code>
Ld /Users/hengchengfei/Library/Developer/Xcode/DerivedData/eval-ebfnwuwnkbqjalczckacolvcfhaq/Build/Products/Debug-iphonesimulator/eval.app/eval normal x86_64
    cd /Users/hengchengfei/Desktop/eval
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -L/Users/hengchengfei/Library/Developer/Xcode/DerivedData/eval-ebfnwuwnkbqjalczckacolvcfhaq/Build/Products/Debug-iphonesimulator -L/Users/hengchengfei/Desktop/eval/Pods/ShareSDK3/libraries/extends/SinaWeiboSDK -L/Users/hengchengfei/Desktop/eval/Pods/ShareSDK3/libraries/extends/WeChatSDK -L/Users/hengchengfei/Desktop/eval/eval/Third/ShareSDK/extends/SinaWeiboSDK -L/Users/hengchengfei/Desktop/eval/eval/Third/ShareSDK/extends/QQSDK -L/Users/hengchengfei/Desktop/eval/eval/Third/ShareSDK/extends/WeChatSDK -L/Users/hengchengfei/Desktop/eval/eval/Third/UMAnalytics_Sdk_3.6.4 -F/Users/hengchengfei/Library/Developer/Xcode/DerivedData/eval-ebfnwuwnkbqjalczckacolvcfhaq/Build/Products/Debug-iphonesimulator -F/Users/hengchengfei/Desktop/eval/Pods/ShareSDK3/libraries -F/Users/hengchengfei/Desktop/eval/Pods/ShareSDK3/libraries/extends/QQSDK -F/Users/hengchengfei/Desktop/eval -F/Users/hengchengfei/Desktop/eval/eval/Third -F/Users/hengchengfei/Desktop/eval/eval/Third/ShareSDK -F/Users/hengchengfei/Desktop/eval/eval/Third/ShareSDK/extends/QQSDK -filelist /Users/hengchengfei/Library/Developer/Xcode/DerivedData/eval-ebfnwuwnkbqjalczckacolvcfhaq/Build/Intermediates/eval.build/Debug-iphonesimulator/eval.build/Objects-normal/x86_64/eval.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=8.0 -Xlinker -objc_abi_version -Xlinker 2 -ObjC -lWeChatSDK -lWeiboSDK -licucore -lsqlite3 -lstdc++ -lz -lz.1.2.5 -framework AFNetworking -framework AdSupport -framework Alamofire -framework CryptoSwift -framework DZNEmptyDataSet -framework HappyDNS -framework IOStickyHeader -framework ImageIO -framework JGProgressHUD -framework JavaScriptCore -framework MMPopupView -framework Masonry -framework ObjectMapper -framework Qiniu -framework Realm -framework SDWebImage -framework ShareSDK -framework ShareSDKConnector -framework ShareSDKExtension -framework Spring -framework TencentOpenAPI -framework UIKit -framework XCGLogger -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/hengchengfei/Library/Developer/Xcode/DerivedData/eval-ebfnwuwnkbqjalczckacolvcfhaq/Build/Intermediates/eval.build/Debug-iphonesimulator/eval.build/Objects-normal/x86_64/eval.swiftmodule -framework AdSupport -framework evalModel -framework Security -framework AssetsLibrary -framework MMPopupView -framework evalCommon -framework IOStickyHeader -framework Qiniu -lz.1 -framework XCGLogger -lstdc++.6.0.9 -licucore.A -lMobClickLibrary -framework ImageIO -framework JavaScriptCore -framework QuartzCore -framework CoreFoundation -framework UIKit -framework Foundation -framework evalView -framework CoreGraphics -framework MessageUI -framework Social -lsqlite3 -framework CoreText -framework CoreTelephony -framework SystemConfiguration -framework Pods -Xlinker -dependency_info -Xlinker /Users/hengchengfei/Library/Developer/Xcode/DerivedData/eval-ebfnwuwnkbqjalczckacolvcfhaq/Build/Intermediates/eval.build/Debug-iphonesimulator/eval.build/Objects-normal/x86_64/eval_dependency_info.dat -o /Users/hengchengfei/Library/Developer/Xcode/DerivedData/eval-ebfnwuwnkbqjalczckacolvcfhaq/Build/Products/Debug-iphonesimulator/eval.app/eval

Undefined symbols for architecture x86_64:
  "_MOBFApplicationCrashNotif", referenced from:
      -[SSDKLogService init] in ShareSDK
  "_OBJC_CLASS_$_MOBFAdService", referenced from:
      objc-class-ref in ShareSDK
  "_OBJC_CLASS_$_MOBFApplication", referenced from:
      objc-class-ref in ShareSDK
  "_OBJC_CLASS_$_MOBFData", referenced from:
      objc-class-ref in ShareSDK
      objc-class-ref in ShareSDKConnector
  "_OBJC_CLASS_$_MOBFDataService", referenced from:
      objc-class-ref in ShareSDK
      objc-class-ref in ShareSDKExtension
  "_OBJC_CLASS_$_MOBFDate", referenced from:
      objc-class-ref in ShareSDK
  "_OBJC_CLASS_$_MOBFDebug", referenced from:
      objc-class-ref in ShareSDK
      objc-class-ref in ShareSDKConnector
  "_OBJC_CLASS_$_MOBFDevice", referenced from:
      objc-class-ref in ShareSDK
      objc-class-ref in ShareSDKConnector
  "_OBJC_CLASS_$_MOBFErrorMsg", referenced from:
      objc-class-ref in ShareSDK
  "_OBJC_CLASS_$_MOBFErrorReport", referenced from:
      objc-class-ref in ShareSDK
  "_OBJC_CLASS_$_MOBFHttpService", referenced from:
      objc-class-ref in ShareSDK
      objc-class-ref in ShareSDKConnector
  "_OBJC_CLASS_$_MOBFImage", referenced from:
      objc-class-ref in ShareSDKConnector
      objc-class-ref in ShareSDKExtension
  "_OBJC_CLASS_$_MOBFImageService", referenced from:
      objc-class-ref in ShareSDK
      objc-class-ref in ShareSDKConnector
  "_OBJC_CLASS_$_MOBFJSContext", referenced from:
      objc-class-ref in ShareSDK
      objc-class-ref in ShareSDKConnector
      objc-class-ref in ShareSDKExtension
  "_OBJC_CLASS_$_MOBFJson", referenced from:
      objc-class-ref in ShareSDK
      objc-class-ref in ShareSDKConnector
      objc-class-ref in ShareSDKExtension
  "_OBJC_CLASS_$_MOBFNotificationCenter", referenced from:
      objc-class-ref in ShareSDK
  "_OBJC_CLASS_$_MOBFNumber", referenced from:
      objc-class-ref in ShareSDKConnector
  "_OBJC_CLASS_$_MOBFOAuthService", referenced from:
      objc-class-ref in ShareSDKConnector
  "_OBJC_CLASS_$_MOBFPluginManager", referenced from:
      objc-class-ref in ShareSDK
      objc-class-ref in ShareSDKConnector
      objc-class-ref in ShareSDKExtension
  "_OBJC_CLASS_$_MOBFRegex", referenced from:
      objc-class-ref in ShareSDK
      objc-class-ref in ShareSDKConnector
  "_OBJC_CLASS_$_MOBFString", referenced from:
      objc-class-ref in ShareSDK
      objc-class-ref in ShareSDKConnector
      objc-class-ref in ShareSDKExtension
  "_OBJC_CLASS_$_MOBFViewController", referenced from:
      objc-class-ref in ShareSDKConnector
  "_kMOBFHttpMethodGet", referenced from:
      ___29-[SSDKService getServerDate:]_block_invoke in ShareSDK
      -[SSDKService getAllowConnectServer:] in ShareSDK
  "_kMOBFHttpMethodPost", referenced from:
      ___25-[SSDKService getConfig:]_block_invoke in ShareSDK
      ___36-[SSDKService getPlatformAppConfig:]_block_invoke in ShareSDK
      ___32-[SSDKService uploadDeviceInfo:]_block_invoke in ShareSDK
      ___48-[SSDKService uploadProcessInfo:isAll:onResult:]_block_invoke in ShareSDK
      ___33-[SSDKService sendLogs:onResult:]_block_invoke in ShareSDK
      ___55-[SSDKService getShortUrls:user:platformType:onResult:]_block_invoke in ShareSDK
      -[SSDKService uploadDeviceExtInfo:] in ShareSDK
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</code>

**Comment by JinghuangLiu** [comment]
需要加多一条命令：pod 'MOBFoundation'

**Comment by JinghuangLiu** [comment]
集成文档也是有更新这块

**Comment by hengchengfei** [comment]
以前的版本没有加是可以的，所以没注意最近的版本需要添上。
非常感谢了！

**Comment by JinghuangLiu** [comment]
嗯嗯，我们建议还是用最新版本的。

**Comment by JinghuangLiu** [comment]
嗯嗯 好的

发自我的 iPhone
